# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/string_therapy',
                'doc_host': 'https://alix559.github.io',
                'git_url': 'https://github.com/alix559/string_therapy',
                'lib_path': 'string_therapy'},
  'syms': {'string_therapy.core': {'string_therapy.core.foo': ('core.html#foo', 'string_therapy/core.py')}}}
