"""Minimal nbdev scaffold (no public API)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/00_core.ipynb #551b93b3
_: None = None  # keeps module importable without adding to `__all__`
