"""all the functionalities required to manipulate markdown files i.e edit , open when clicked fromt he d3.js note gallery view"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_icon1.ipynb.

# %% auto #0
__all__ = ['NOTEBOOK_INITIAL_MD', 'SESSION_MD_KEY', 'SESSION_EDITOR_KEY', 'NOTEBOOK_ICON_ID', 'NotebookCell', 'parse_to_notebook',
           'notebook_editor_panel', 'icon_panel', 'Icon1VizLayer', 'default_icon1_viz_layer', 'viz', 'register_routes']

# %% ../nbs/02_icon1.ipynb #41d6f782-24fe-4fff-a58d-241cc75bbea2
from dataclasses import dataclass
from typing import Any, Callable

from fasthtml.common import *
from monsterui.all import *
import re

# %% ../nbs/02_icon1.ipynb #ae586227-c047-4c56-9a27-1f294b912f8f
NOTEBOOK_INITIAL_MD = """# Notebook
This is markdown with **MonsterUI** styling.

```python
def hello():
    print("Edit below or click Edit for source.")
```

Click **Edit** for the raw markdown; **Done** returns here."""


def NotebookCell(content, cell_type="markdown"):
    if cell_type == "code":
        return Div(
            Div(P("In [ ]:", cls="text-xs text-muted-foreground absolute -left-12 top-4 font-mono")),
            Card(render_md(content), cls="bg-muted/30 border-l-4 border-l-primary relative"),
            cls="mb-6 ml-12",
        )
    return Div(
        render_md(content),
        cls="mb-6 px-4 prose prose-slate max-w-none",
    )


def parse_to_notebook(md_text):
    pattern = r'(```[\s\S]*?```)'
    parts = re.split(pattern, md_text)

    cells = []
    for part in parts:
        part = part.strip()
        if not part:
            continue
        if part.startswith("```"):
            cells.append(NotebookCell(part, cell_type="code"))
        else:
            cells.append(NotebookCell(part, cell_type="markdown"))
    return Div(*cells, id="notebook-view")


def notebook_editor_panel(md: str):
    return Div(
        H3("Markdown", cls="mb-4"),
        P("Preview updates as you type. **Done** shows the notebook view.", cls="text-sm opacity-70 mb-3"),
        Textarea(
            md,
            id="md-input",
            name="content",
            cls="textarea textarea-bordered w-full min-h-[10rem] flex-1 max-h-full font-mono text-sm resize-y",
            hx_post="/icon/render",
            hx_trigger="keyup changed delay:300ms",
            hx_swap="none",
        ),
        cls="space-y-2 min-w-0 w-full py-2 flex-1 min-h-0 flex flex-col",
    )


def icon_panel(md: str, editor_open: bool):
    """Root fragment; id=icon-panel is the HTMX swap target."""
    edit_btn = Button(
        "Edit",
        cls="btn btn-outline btn-primary btn-sm shrink-0",
        hx_get="/icon/panel?edit=1",
        hx_target="#icon-panel",
        hx_swap="outerHTML",
    )
    done_btn = Button(
        "Done",
        cls="btn btn-outline btn-primary btn-sm shrink-0",
        hx_get="/icon/panel?edit=0",
        hx_target="#icon-panel",
        hx_swap="outerHTML",
    )
    header = Div(
        H2("Notebook", cls="text-2xl font-bold truncate min-w-0"),
        Div(
            done_btn if editor_open else edit_btn,
            cls="flex items-center gap-2 shrink-0",
        ),
        cls="flex flex-row justify-between items-center gap-2 mb-2 w-full",
    )
    if editor_open:
        body = notebook_editor_panel(md)
    else:
        body = Div(
            parse_to_notebook(md),
            cls="w-full min-w-0 py-2 flex-1 min-h-0 overflow-y-auto",
        )
    return Div(
        header,
        body,
        id="icon-panel",
        cls="relative p-4 w-full h-full min-h-0 flex flex-col overflow-hidden",
    )


# %% ../nbs/02_icon1.ipynb #6d7ba7a0
@dataclass(frozen=True)
class Icon1VizLayer:
    """Injectable notebook UI (same role as ``visualizations.icon1.viz`` in string therapy1)."""

    notebook_initial_md: str
    icon_panel: Callable[[str, bool], Any]
    parse_to_notebook: Callable[[str], Any]


def default_icon1_viz_layer() -> Icon1VizLayer:
    return Icon1VizLayer(
        notebook_initial_md=NOTEBOOK_INITIAL_MD,
        icon_panel=icon_panel,
        parse_to_notebook=parse_to_notebook,
    )

# %% ../nbs/02_icon1.ipynb #76496a82-82c9-4b0d-984a-364793c349ab
SESSION_MD_KEY = "notebook_md"
SESSION_EDITOR_KEY = "notebook_editor_open"
NOTEBOOK_ICON_ID = 1


def _md(session: dict, layer: Icon1VizLayer) -> str:
    return session.get(SESSION_MD_KEY) or layer.notebook_initial_md


def viz(sid: str, session: dict, viz_layer: Icon1VizLayer | None = None):
    layer = viz_layer or default_icon1_viz_layer()
    session[SESSION_EDITOR_KEY] = False
    return layer.icon_panel(_md(session, layer), False)


def register_routes(app, viz_layer: Icon1VizLayer | None = None):
    layer = viz_layer or default_icon1_viz_layer()

    @app.get("/icon/panel")
    def notebook_panel_route(session, edit: str | None = None):
        if edit == "1":
            session[SESSION_EDITOR_KEY] = True
        elif edit == "0":
            session[SESSION_EDITOR_KEY] = False
        return layer.icon_panel(_md(session, layer), session.get(SESSION_EDITOR_KEY, False))

    @app.post("/icon/render")
    def notebook_render(content: str, session):
        session[SESSION_MD_KEY] = content
        return layer.parse_to_notebook(content)
