# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_lisette.ipynb.

# %% ../nbs/03_lisette.ipynb #9f56d16a-cc80-4431-ada9-099e4179286c
from __future__ import annotations
from typing import Any, Dict, List, Optional, Sequence

import os
import sys


def _unshadow_pypi_lisette() -> None:
    """If ``lisette.py`` sits in the process cwd, it shadows the PyPI ``lisette`` package."""
    root = os.getcwd()
    if not sys.path:
        return
    head = sys.path[0]
    if head in ("", root) and os.path.isfile(os.path.join(root, "lisette.py")):
        if not os.path.isdir(os.path.join(root, "lisette")):
            sys.path.pop(0)


_unshadow_pypi_lisette()
from lisette.core import Chat

import string_therapy.therapy_config as tc


# %% auto #0
__all__ = ['lisette_chat']

# %% ../nbs/03_lisette.ipynb #a6d1df6e-2160-4921-839d-eec875a55b9b
_chats: Dict[tuple[str, str], object] = {}


def _load_dotenv() -> None:
    tc.load_environment()

def _sync_claude_api_key() -> None:
    k = os.getenv("CLAUDE_API_KEY")

def _model() -> str :
    _load_dotenv() 
    if os.getenv("CLAUDE_API_KEY"):
        return "claude-sonnet-4-5-20250929"

def _get_chat(
    sid : str, 
    *, 
    variant: str = "default",
    tools: Optional[Sequence[Any]] = None, 
    sp: str = "",
):
    _load_dotenv()
    _sync_claude_api_key()
    key = (sid, variant)
    if key not in _chats:
        kw: dict = {}
        if tools:
            kw["tools"] = list(tools)
        if sp:
            kw["sp"] = sp 
        _chats[key] = Chat(_model(), **kw)
    return _chats[key]


def _cts(r: Any) -> str:
    """
    Assistant text from a LiteLLM / OpenAI-shaped completion
    """
    mc = r.choices[0].message.content
    if isinstance(mc, list):
        part: list[str] = []
        for block in mc:
            if isinstance(block, dict) and block.get("type") == "text":
                parts.append(str(block.get("text", "")))
        joined = "".join(parts)
        return joined if joined else str(mc)
    return str(mc) if mc is not None else ""
    
    
def lisette_chat(
    sid: str, 
    msg: str, 
    *, 
    max_tokens: int, 
    variant: str = "default", 
    tools: Optional[List[Any]] = None, 
    sp: str = "",
    max_steps: int = 2, 
    ) -> str :
    try:
        chat = _get_chat(sid, variant=variant, tools=tools, sp=sp)
    except ImportError:
        return ("Lisette is not installed")

    r = chat(msg.strip(), max_tokens=max_tokens, max_steps=max_steps)
    try : 
        return _cts(r)
    except (AttributeError, IndexError, TypeError):
        return str(r)
    

